//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.261.
// 
#pragma warning disable 1591

namespace BillPaymentForm.FDGGWSApiOrderService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FDGGWSApiOrderBinding", Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/fdggwsapi")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Options))]
    public partial class FDGGWSApiOrderService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FDGGWSApiActionOperationCompleted;
        
        private System.Threading.SendOrPostCallback FDGGWSApiOrderOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FDGGWSApiOrderService() {
            this.Url = global::BillPaymentForm.Properties.Settings.Default.BillPaymentForm_FDGGWSApiOrderService_FDGGWSApiOrderService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FDGGWSApiActionCompletedEventHandler FDGGWSApiActionCompleted;
        
        /// <remarks/>
        public event FDGGWSApiOrderCompletedEventHandler FDGGWSApiOrderCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("FDGGWSApiActionResponse", Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/fdggwsapi")]
        public FDGGWSApiActionResponse FDGGWSApiAction([System.Xml.Serialization.XmlElementAttribute(Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/fdggwsapi")] FDGGWSApiActionRequest FDGGWSApiActionRequest) {
            object[] results = this.Invoke("FDGGWSApiAction", new object[] {
                        FDGGWSApiActionRequest});
            return ((FDGGWSApiActionResponse)(results[0]));
        }
        
        /// <remarks/>
        public void FDGGWSApiActionAsync(FDGGWSApiActionRequest FDGGWSApiActionRequest) {
            this.FDGGWSApiActionAsync(FDGGWSApiActionRequest, null);
        }
        
        /// <remarks/>
        public void FDGGWSApiActionAsync(FDGGWSApiActionRequest FDGGWSApiActionRequest, object userState) {
            if ((this.FDGGWSApiActionOperationCompleted == null)) {
                this.FDGGWSApiActionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFDGGWSApiActionOperationCompleted);
            }
            this.InvokeAsync("FDGGWSApiAction", new object[] {
                        FDGGWSApiActionRequest}, this.FDGGWSApiActionOperationCompleted, userState);
        }
        
        private void OnFDGGWSApiActionOperationCompleted(object arg) {
            if ((this.FDGGWSApiActionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FDGGWSApiActionCompleted(this, new FDGGWSApiActionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("FDGGWSApiOrderResponse", Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/fdggwsapi")]
        public FDGGWSApiOrderResponse FDGGWSApiOrder([System.Xml.Serialization.XmlElementAttribute(Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/fdggwsapi")] FDGGWSApiOrderRequest FDGGWSApiOrderRequest) {
            object[] results = this.Invoke("FDGGWSApiOrder", new object[] {
                        FDGGWSApiOrderRequest});
            return ((FDGGWSApiOrderResponse)(results[0]));
        }
        
        /// <remarks/>
        public void FDGGWSApiOrderAsync(FDGGWSApiOrderRequest FDGGWSApiOrderRequest) {
            this.FDGGWSApiOrderAsync(FDGGWSApiOrderRequest, null);
        }
        
        /// <remarks/>
        public void FDGGWSApiOrderAsync(FDGGWSApiOrderRequest FDGGWSApiOrderRequest, object userState) {
            if ((this.FDGGWSApiOrderOperationCompleted == null)) {
                this.FDGGWSApiOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFDGGWSApiOrderOperationCompleted);
            }
            this.InvokeAsync("FDGGWSApiOrder", new object[] {
                        FDGGWSApiOrderRequest}, this.FDGGWSApiOrderOperationCompleted, userState);
        }
        
        private void OnFDGGWSApiOrderOperationCompleted(object arg) {
            if ((this.FDGGWSApiOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FDGGWSApiOrderCompleted(this, new FDGGWSApiOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/fdggwsapi")]
    public partial class FDGGWSApiActionRequest {
        
        private Action itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Action", Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/a1")]
        public Action Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/a1")]
    public partial class Action {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RecurringPayment", typeof(RecurringPayment))]
        [System.Xml.Serialization.XmlElementAttribute("SystemCheck", typeof(SystemCheck))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/a1")]
    public partial class RecurringPayment {
        
        private RecurringPaymentFunction functionField;
        
        private string orderIdField;
        
        private string storeIdField;
        
        private Billing billingField;
        
        private Shipping shippingField;
        
        private RecurringPaymentInformation recurringPaymentInformationField;
        
        private RecurringPaymentTransactionDataType transactionDataTypeField;
        
        private TransactionDetails transactionDetailsField;
        
        private Payment paymentField;
        
        private Notes notesField;
        
        private ItemListItemEntry[] itemListField;
        
        /// <remarks/>
        public RecurringPaymentFunction Function {
            get {
                return this.functionField;
            }
            set {
                this.functionField = value;
            }
        }
        
        /// <remarks/>
        public string OrderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        public string StoreId {
            get {
                return this.storeIdField;
            }
            set {
                this.storeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
        public Billing Billing {
            get {
                return this.billingField;
            }
            set {
                this.billingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
        public Shipping Shipping {
            get {
                return this.shippingField;
            }
            set {
                this.shippingField = value;
            }
        }
        
        /// <remarks/>
        public RecurringPaymentInformation RecurringPaymentInformation {
            get {
                return this.recurringPaymentInformationField;
            }
            set {
                this.recurringPaymentInformationField = value;
            }
        }
        
        /// <remarks/>
        public RecurringPaymentTransactionDataType TransactionDataType {
            get {
                return this.transactionDataTypeField;
            }
            set {
                this.transactionDataTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
        public TransactionDetails TransactionDetails {
            get {
                return this.transactionDetailsField;
            }
            set {
                this.transactionDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
        public Payment Payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
        public Notes Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
        [System.Xml.Serialization.XmlArrayItemAttribute("ItemEntry", IsNullable=false)]
        public ItemListItemEntry[] ItemList {
            get {
                return this.itemListField;
            }
            set {
                this.itemListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/a1")]
    public enum RecurringPaymentFunction {
        
        /// <remarks/>
        cancel,
        
        /// <remarks/>
        install,
        
        /// <remarks/>
        modify,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
    public partial class Billing {
        
        private string customerIDField;
        
        private string nameField;
        
        private string companyField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private string countryField;
        
        private string phoneField;
        
        private string faxField;
        
        private string emailField;
        
        /// <remarks/>
        public string CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TeleCheckTxType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreditCardTxType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CalculateShipping))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CalculateTax))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
    public partial class Options {
        
        private string storeIdField;
        
        /// <remarks/>
        public string StoreId {
            get {
                return this.storeIdField;
            }
            set {
                this.storeIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
    public partial class TeleCheckTxType : Options {
        
        private TeleCheckTxTypeType typeField;
        
        /// <remarks/>
        public TeleCheckTxTypeType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
    public enum TeleCheckTxTypeType {
        
        /// <remarks/>
        @return,
        
        /// <remarks/>
        sale,
        
        /// <remarks/>
        @void,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
    public partial class CreditCardTxType : Options {
        
        private CreditCardTxTypeType typeField;
        
        private CreditCardTxTypeResult resultField;
        
        private bool resultFieldSpecified;
        
        /// <remarks/>
        public CreditCardTxTypeType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public CreditCardTxTypeResult result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultSpecified {
            get {
                return this.resultFieldSpecified;
            }
            set {
                this.resultFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
    public enum CreditCardTxTypeType {
        
        /// <remarks/>
        credit,
        
        /// <remarks/>
        forceTicket,
        
        /// <remarks/>
        postAuth,
        
        /// <remarks/>
        preAuth,
        
        /// <remarks/>
        @return,
        
        /// <remarks/>
        sale,
        
        /// <remarks/>
        @void,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
    public enum CreditCardTxTypeResult {
        
        /// <remarks/>
        Duplicate,
        
        /// <remarks/>
        Decline,
        
        /// <remarks/>
        Good,
        
        /// <remarks/>
        Live,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
    public partial class CalculateShipping : Options {
        
        private double subTotalField;
        
        private bool subTotalFieldSpecified;
        
        private double weightField;
        
        private bool weightFieldSpecified;
        
        private string itemCountField;
        
        private string carrierTypeField;
        
        private string shipStateField;
        
        private string shipZipField;
        
        private string shipCountryField;
        
        /// <remarks/>
        public double SubTotal {
            get {
                return this.subTotalField;
            }
            set {
                this.subTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SubTotalSpecified {
            get {
                return this.subTotalFieldSpecified;
            }
            set {
                this.subTotalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeightSpecified {
            get {
                return this.weightFieldSpecified;
            }
            set {
                this.weightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ItemCount {
            get {
                return this.itemCountField;
            }
            set {
                this.itemCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string CarrierType {
            get {
                return this.carrierTypeField;
            }
            set {
                this.carrierTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ShipState {
            get {
                return this.shipStateField;
            }
            set {
                this.shipStateField = value;
            }
        }
        
        /// <remarks/>
        public string ShipZip {
            get {
                return this.shipZipField;
            }
            set {
                this.shipZipField = value;
            }
        }
        
        /// <remarks/>
        public string ShipCountry {
            get {
                return this.shipCountryField;
            }
            set {
                this.shipCountryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
    public partial class CalculateTax : Options {
        
        private double subTotalField;
        
        private bool subTotalFieldSpecified;
        
        private string shipStateField;
        
        private string shipZipField;
        
        /// <remarks/>
        public double SubTotal {
            get {
                return this.subTotalField;
            }
            set {
                this.subTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SubTotalSpecified {
            get {
                return this.subTotalFieldSpecified;
            }
            set {
                this.subTotalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ShipState {
            get {
                return this.shipStateField;
            }
            set {
                this.shipStateField = value;
            }
        }
        
        /// <remarks/>
        public string ShipZip {
            get {
                return this.shipZipField;
            }
            set {
                this.shipZipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
    public partial class Transaction {
        
        private object[] itemsField;
        
        private Payment paymentField;
        
        private TransactionDetails transactionDetailsField;
        
        private Billing billingField;
        
        private Shipping shippingField;
        
        private Notes notesField;
        
        private ItemListItemEntry[] itemListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CalculateShipping", typeof(CalculateShipping))]
        [System.Xml.Serialization.XmlElementAttribute("CalculateTax", typeof(CalculateTax))]
        [System.Xml.Serialization.XmlElementAttribute("CreditCard3DSecure", typeof(CreditCard3DSecure))]
        [System.Xml.Serialization.XmlElementAttribute("CreditCardData", typeof(CreditCardData))]
        [System.Xml.Serialization.XmlElementAttribute("CreditCardTxType", typeof(CreditCardTxType))]
        [System.Xml.Serialization.XmlElementAttribute("TeleCheckData", typeof(TeleCheckData))]
        [System.Xml.Serialization.XmlElementAttribute("TeleCheckTxType", typeof(TeleCheckTxType))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        public Payment Payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
            }
        }
        
        /// <remarks/>
        public TransactionDetails TransactionDetails {
            get {
                return this.transactionDetailsField;
            }
            set {
                this.transactionDetailsField = value;
            }
        }
        
        /// <remarks/>
        public Billing Billing {
            get {
                return this.billingField;
            }
            set {
                this.billingField = value;
            }
        }
        
        /// <remarks/>
        public Shipping Shipping {
            get {
                return this.shippingField;
            }
            set {
                this.shippingField = value;
            }
        }
        
        /// <remarks/>
        public Notes Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ItemEntry", IsNullable=false)]
        public ItemListItemEntry[] ItemList {
            get {
                return this.itemListField;
            }
            set {
                this.itemListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
    public partial class CreditCard3DSecure {
        
        private CreditCard3DSecurePayerSecurityLevel payerSecurityLevelField;
        
        private bool payerSecurityLevelFieldSpecified;
        
        private string authenticationValueField;
        
        private string xIDField;
        
        /// <remarks/>
        public CreditCard3DSecurePayerSecurityLevel PayerSecurityLevel {
            get {
                return this.payerSecurityLevelField;
            }
            set {
                this.payerSecurityLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PayerSecurityLevelSpecified {
            get {
                return this.payerSecurityLevelFieldSpecified;
            }
            set {
                this.payerSecurityLevelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string AuthenticationValue {
            get {
                return this.authenticationValueField;
            }
            set {
                this.authenticationValueField = value;
            }
        }
        
        /// <remarks/>
        public string XID {
            get {
                return this.xIDField;
            }
            set {
                this.xIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
    public enum CreditCard3DSecurePayerSecurityLevel {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("06")]
        Item06,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("07")]
        Item07,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
    public partial class CreditCardData {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CardCodeIndicator", typeof(CreditCardDataCardCodeIndicator))]
        [System.Xml.Serialization.XmlElementAttribute("CardCodeValue", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("CardNumber", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ExpMonth", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ExpYear", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("TrackData", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
    public enum CreditCardDataCardCodeIndicator {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
        
        /// <remarks/>
        NOT_PROVIDED,
        
        /// <remarks/>
        PROVIDED,
        
        /// <remarks/>
        ILLEGIBLE,
        
        /// <remarks/>
        NO_IMPRINT,
        
        /// <remarks/>
        NOT_PRESENT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        CardCodeIndicator,
        
        /// <remarks/>
        CardCodeValue,
        
        /// <remarks/>
        CardNumber,
        
        /// <remarks/>
        ExpMonth,
        
        /// <remarks/>
        ExpYear,
        
        /// <remarks/>
        TrackData,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
    public partial class TeleCheckData {
        
        private string checkNumberField;
        
        private AccountType accountTypeField;
        
        private bool accountTypeFieldSpecified;
        
        private string accountNumberField;
        
        private string routingNumberField;
        
        private string socialSecurityNumberField;
        
        private string drivingLicenseNumberField;
        
        private string drivingLicenseStateField;
        
        private string bankNameField;
        
        private string bankStateField;
        
        /// <remarks/>
        public string CheckNumber {
            get {
                return this.checkNumberField;
            }
            set {
                this.checkNumberField = value;
            }
        }
        
        /// <remarks/>
        public AccountType AccountType {
            get {
                return this.accountTypeField;
            }
            set {
                this.accountTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccountTypeSpecified {
            get {
                return this.accountTypeFieldSpecified;
            }
            set {
                this.accountTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string RoutingNumber {
            get {
                return this.routingNumberField;
            }
            set {
                this.routingNumberField = value;
            }
        }
        
        /// <remarks/>
        public string SocialSecurityNumber {
            get {
                return this.socialSecurityNumberField;
            }
            set {
                this.socialSecurityNumberField = value;
            }
        }
        
        /// <remarks/>
        public string DrivingLicenseNumber {
            get {
                return this.drivingLicenseNumberField;
            }
            set {
                this.drivingLicenseNumberField = value;
            }
        }
        
        /// <remarks/>
        public string DrivingLicenseState {
            get {
                return this.drivingLicenseStateField;
            }
            set {
                this.drivingLicenseStateField = value;
            }
        }
        
        /// <remarks/>
        public string BankName {
            get {
                return this.bankNameField;
            }
            set {
                this.bankNameField = value;
            }
        }
        
        /// <remarks/>
        public string BankState {
            get {
                return this.bankStateField;
            }
            set {
                this.bankStateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
    public enum AccountType {
        
        /// <remarks/>
        pc,
        
        /// <remarks/>
        ps,
        
        /// <remarks/>
        bc,
        
        /// <remarks/>
        bs,
        
        /// <remarks/>
        PC,
        
        /// <remarks/>
        PS,
        
        /// <remarks/>
        BC,
        
        /// <remarks/>
        BS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
    public partial class Payment {
        
        private string hostedDataIDField;
        
        private decimal chargeTotalField;
        
        private decimal subTotalField;
        
        private bool subTotalFieldSpecified;
        
        private decimal taxField;
        
        private bool taxFieldSpecified;
        
        private decimal vATTaxField;
        
        private bool vATTaxFieldSpecified;
        
        private decimal shippingField;
        
        private bool shippingFieldSpecified;
        
        /// <remarks/>
        public string HostedDataID {
            get {
                return this.hostedDataIDField;
            }
            set {
                this.hostedDataIDField = value;
            }
        }
        
        /// <remarks/>
        public decimal ChargeTotal {
            get {
                return this.chargeTotalField;
            }
            set {
                this.chargeTotalField = value;
            }
        }
        
        /// <remarks/>
        public decimal SubTotal {
            get {
                return this.subTotalField;
            }
            set {
                this.subTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SubTotalSpecified {
            get {
                return this.subTotalFieldSpecified;
            }
            set {
                this.subTotalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Tax {
            get {
                return this.taxField;
            }
            set {
                this.taxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TaxSpecified {
            get {
                return this.taxFieldSpecified;
            }
            set {
                this.taxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal VATTax {
            get {
                return this.vATTaxField;
            }
            set {
                this.vATTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VATTaxSpecified {
            get {
                return this.vATTaxFieldSpecified;
            }
            set {
                this.vATTaxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Shipping {
            get {
                return this.shippingField;
            }
            set {
                this.shippingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShippingSpecified {
            get {
                return this.shippingFieldSpecified;
            }
            set {
                this.shippingFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
    public partial class TransactionDetails {
        
        private string userIDField;
        
        private string invoiceNumberField;
        
        private string orderIdField;
        
        private string ipField;
        
        private string referenceNumberField;
        
        private string tDateField;
        
        private Recurring recurringField;
        
        private bool recurringFieldSpecified;
        
        private TaxExempt taxExemptField;
        
        private bool taxExemptFieldSpecified;
        
        private TerminalType terminalTypeField;
        
        private bool terminalTypeFieldSpecified;
        
        private TransactionDetailsTransactionOrigin transactionOriginField;
        
        private string pONumberField;
        
        private string deviceIDField;
        
        public TransactionDetails() {
            this.recurringField = Recurring.No;
            this.taxExemptField = TaxExempt.No;
            this.transactionOriginField = TransactionDetailsTransactionOrigin.ECI;
        }
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string OrderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        public string Ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string TDate {
            get {
                return this.tDateField;
            }
            set {
                this.tDateField = value;
            }
        }
        
        /// <remarks/>
        public Recurring Recurring {
            get {
                return this.recurringField;
            }
            set {
                this.recurringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecurringSpecified {
            get {
                return this.recurringFieldSpecified;
            }
            set {
                this.recurringFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TaxExempt TaxExempt {
            get {
                return this.taxExemptField;
            }
            set {
                this.taxExemptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TaxExemptSpecified {
            get {
                return this.taxExemptFieldSpecified;
            }
            set {
                this.taxExemptFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TerminalType TerminalType {
            get {
                return this.terminalTypeField;
            }
            set {
                this.terminalTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TerminalTypeSpecified {
            get {
                return this.terminalTypeFieldSpecified;
            }
            set {
                this.terminalTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(TransactionDetailsTransactionOrigin.ECI)]
        public TransactionDetailsTransactionOrigin TransactionOrigin {
            get {
                return this.transactionOriginField;
            }
            set {
                this.transactionOriginField = value;
            }
        }
        
        /// <remarks/>
        public string PONumber {
            get {
                return this.pONumberField;
            }
            set {
                this.pONumberField = value;
            }
        }
        
        /// <remarks/>
        public string DeviceID {
            get {
                return this.deviceIDField;
            }
            set {
                this.deviceIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
    public enum Recurring {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
    public enum TaxExempt {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
    public enum TerminalType {
        
        /// <remarks/>
        Standalone,
        
        /// <remarks/>
        Unspecified,
        
        /// <remarks/>
        POS,
        
        /// <remarks/>
        Unattended,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
    public enum TransactionDetailsTransactionOrigin {
        
        /// <remarks/>
        ECI,
        
        /// <remarks/>
        MOTO,
        
        /// <remarks/>
        RETAIL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
    public partial class Shipping {
        
        private double weightField;
        
        private bool weightFieldSpecified;
        
        private decimal itemsField;
        
        private bool itemsFieldSpecified;
        
        private decimal carrierField;
        
        private bool carrierFieldSpecified;
        
        private double totalField;
        
        private bool totalFieldSpecified;
        
        private string typeField;
        
        private string nameField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private string countryField;
        
        /// <remarks/>
        public double Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeightSpecified {
            get {
                return this.weightFieldSpecified;
            }
            set {
                this.weightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemsSpecified {
            get {
                return this.itemsFieldSpecified;
            }
            set {
                this.itemsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Carrier {
            get {
                return this.carrierField;
            }
            set {
                this.carrierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CarrierSpecified {
            get {
                return this.carrierFieldSpecified;
            }
            set {
                this.carrierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSpecified {
            get {
                return this.totalFieldSpecified;
            }
            set {
                this.totalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
    public partial class Notes {
        
        private string commentsField;
        
        private string referredByField;
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        public string ReferredBy {
            get {
                return this.referredByField;
            }
            set {
                this.referredByField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
    public partial class ItemListItemEntry {
        
        private string idField;
        
        private string descriptionField;
        
        private string priceField;
        
        private string quantityField;
        
        private string serialField;
        
        private string eSDtypeField;
        
        private string softfileField;
        
        private ItemListItemEntryOptionEntry[] optionListField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public string Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public string Serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
            }
        }
        
        /// <remarks/>
        public string ESDtype {
            get {
                return this.eSDtypeField;
            }
            set {
                this.eSDtypeField = value;
            }
        }
        
        /// <remarks/>
        public string Softfile {
            get {
                return this.softfileField;
            }
            set {
                this.softfileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("OptionEntry", IsNullable=false)]
        public ItemListItemEntryOptionEntry[] OptionList {
            get {
                return this.optionListField;
            }
            set {
                this.optionListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
    public partial class ItemListItemEntryOptionEntry {
        
        private string optionNameField;
        
        private string optionValueField;
        
        /// <remarks/>
        public string OptionName {
            get {
                return this.optionNameField;
            }
            set {
                this.optionNameField = value;
            }
        }
        
        /// <remarks/>
        public string OptionValue {
            get {
                return this.optionValueField;
            }
            set {
                this.optionValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/a1")]
    public partial class RecurringPaymentInformation {
        
        private string recurringStartDateField;
        
        private string installmentCountField;
        
        private string maximumFailuresField;
        
        private string installmentFrequencyField;
        
        private RecurringPaymentInformationInstallmentPeriod installmentPeriodField;
        
        private bool installmentPeriodFieldSpecified;
        
        /// <remarks/>
        public string RecurringStartDate {
            get {
                return this.recurringStartDateField;
            }
            set {
                this.recurringStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string InstallmentCount {
            get {
                return this.installmentCountField;
            }
            set {
                this.installmentCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string MaximumFailures {
            get {
                return this.maximumFailuresField;
            }
            set {
                this.maximumFailuresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string InstallmentFrequency {
            get {
                return this.installmentFrequencyField;
            }
            set {
                this.installmentFrequencyField = value;
            }
        }
        
        /// <remarks/>
        public RecurringPaymentInformationInstallmentPeriod InstallmentPeriod {
            get {
                return this.installmentPeriodField;
            }
            set {
                this.installmentPeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InstallmentPeriodSpecified {
            get {
                return this.installmentPeriodFieldSpecified;
            }
            set {
                this.installmentPeriodFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/a1")]
    public enum RecurringPaymentInformationInstallmentPeriod {
        
        /// <remarks/>
        day,
        
        /// <remarks/>
        week,
        
        /// <remarks/>
        month,
        
        /// <remarks/>
        year,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/a1")]
    public partial class RecurringPaymentTransactionDataType {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CreditCardData", typeof(CreditCardData))]
        [System.Xml.Serialization.XmlElementAttribute("TeleCheckData", typeof(TeleCheckData))]
        [System.Xml.Serialization.XmlElementAttribute("CreditCard3DSecure", typeof(CreditCard3DSecure), Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/a1")]
    public partial class SystemCheck {
        
        private string storeIdField;
        
        /// <remarks/>
        public string StoreId {
            get {
                return this.storeIdField;
            }
            set {
                this.storeIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/fdggwsapi")]
    public partial class FDGGWSApiActionResponse {
        
        private bool successField;
        
        private string approvalCodeField;
        
        private string aVSResponseField;
        
        private string commercialServiceProviderField;
        
        private string errorMessageField;
        
        private string orderIdField;
        
        private string processorApprovalCodeField;
        
        private string processorReceiptNumberField;
        
        private string processorReferenceNumberField;
        
        private string processorResponseCodeField;
        
        private string processorResponseMessageField;
        
        private string processorTraceNumberField;
        
        private string tDateField;
        
        private string terminalIDField;
        
        private string transactionResultField;
        
        private string transactionTimeField;
        
        private string transactionIDField;
        
        private string transactionScoreField;
        
        private string fraudActionField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ApprovalCode {
            get {
                return this.approvalCodeField;
            }
            set {
                this.approvalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string AVSResponse {
            get {
                return this.aVSResponseField;
            }
            set {
                this.aVSResponseField = value;
            }
        }
        
        /// <remarks/>
        public string CommercialServiceProvider {
            get {
                return this.commercialServiceProviderField;
            }
            set {
                this.commercialServiceProviderField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string OrderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessorApprovalCode {
            get {
                return this.processorApprovalCodeField;
            }
            set {
                this.processorApprovalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessorReceiptNumber {
            get {
                return this.processorReceiptNumberField;
            }
            set {
                this.processorReceiptNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessorReferenceNumber {
            get {
                return this.processorReferenceNumberField;
            }
            set {
                this.processorReferenceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessorResponseCode {
            get {
                return this.processorResponseCodeField;
            }
            set {
                this.processorResponseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessorResponseMessage {
            get {
                return this.processorResponseMessageField;
            }
            set {
                this.processorResponseMessageField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessorTraceNumber {
            get {
                return this.processorTraceNumberField;
            }
            set {
                this.processorTraceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string TDate {
            get {
                return this.tDateField;
            }
            set {
                this.tDateField = value;
            }
        }
        
        /// <remarks/>
        public string TerminalID {
            get {
                return this.terminalIDField;
            }
            set {
                this.terminalIDField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionResult {
            get {
                return this.transactionResultField;
            }
            set {
                this.transactionResultField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionTime {
            get {
                return this.transactionTimeField;
            }
            set {
                this.transactionTimeField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionScore {
            get {
                return this.transactionScoreField;
            }
            set {
                this.transactionScoreField = value;
            }
        }
        
        /// <remarks/>
        public string FraudAction {
            get {
                return this.fraudActionField;
            }
            set {
                this.fraudActionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/fdggwsapi")]
    public partial class FDGGWSApiOrderRequest {
        
        private Transaction itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Transaction", Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/v1")]
        public Transaction Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://secure.linkpt.net/fdggwsapi/schemas_us/fdggwsapi")]
    public partial class FDGGWSApiOrderResponse {
        
        private string approvalCodeField;
        
        private string aVSResponseField;
        
        private string commercialServiceProviderField;
        
        private string errorMessageField;
        
        private string orderIdField;
        
        private string processorApprovalCodeField;
        
        private string processorReferenceNumberField;
        
        private string processorResponseCodeField;
        
        private string processorResponseMessageField;
        
        private string tDateField;
        
        private string transactionResultField;
        
        private string transactionTimeField;
        
        private string transactionIDField;
        
        private string calculatedTaxField;
        
        private string calculatedShippingField;
        
        private string transactionScoreField;
        
        private string authenticationResponseCodeField;
        
        private string fraudActionField;
        
        /// <remarks/>
        public string ApprovalCode {
            get {
                return this.approvalCodeField;
            }
            set {
                this.approvalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string AVSResponse {
            get {
                return this.aVSResponseField;
            }
            set {
                this.aVSResponseField = value;
            }
        }
        
        /// <remarks/>
        public string CommercialServiceProvider {
            get {
                return this.commercialServiceProviderField;
            }
            set {
                this.commercialServiceProviderField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string OrderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessorApprovalCode {
            get {
                return this.processorApprovalCodeField;
            }
            set {
                this.processorApprovalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessorReferenceNumber {
            get {
                return this.processorReferenceNumberField;
            }
            set {
                this.processorReferenceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessorResponseCode {
            get {
                return this.processorResponseCodeField;
            }
            set {
                this.processorResponseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessorResponseMessage {
            get {
                return this.processorResponseMessageField;
            }
            set {
                this.processorResponseMessageField = value;
            }
        }
        
        /// <remarks/>
        public string TDate {
            get {
                return this.tDateField;
            }
            set {
                this.tDateField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionResult {
            get {
                return this.transactionResultField;
            }
            set {
                this.transactionResultField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionTime {
            get {
                return this.transactionTimeField;
            }
            set {
                this.transactionTimeField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        public string CalculatedTax {
            get {
                return this.calculatedTaxField;
            }
            set {
                this.calculatedTaxField = value;
            }
        }
        
        /// <remarks/>
        public string CalculatedShipping {
            get {
                return this.calculatedShippingField;
            }
            set {
                this.calculatedShippingField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionScore {
            get {
                return this.transactionScoreField;
            }
            set {
                this.transactionScoreField = value;
            }
        }
        
        /// <remarks/>
        public string AuthenticationResponseCode {
            get {
                return this.authenticationResponseCodeField;
            }
            set {
                this.authenticationResponseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string FraudAction {
            get {
                return this.fraudActionField;
            }
            set {
                this.fraudActionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FDGGWSApiActionCompletedEventHandler(object sender, FDGGWSApiActionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FDGGWSApiActionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FDGGWSApiActionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FDGGWSApiActionResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FDGGWSApiActionResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FDGGWSApiOrderCompletedEventHandler(object sender, FDGGWSApiOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FDGGWSApiOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FDGGWSApiOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FDGGWSApiOrderResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FDGGWSApiOrderResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591